version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    ignore:
      - dependency-name: "serial_test"
        # ignore those versions, as they still make our test suite fail
        # check this issue for progress on this: https://github.com/palfrey/serial_test/issues/68
        versions: ["0.7.x", "0.8.x"]
