name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests-linux:
    strategy:
      matrix:
        include:
          - project: "tremor-runtime"
            covname: runtime
            features: "--features integration"
          - project: "tremor-api"
            covname: api
          - project: "tremor-cli"
            covname: cli
          - project: "tremor-common"
            covname: common
          - project: "tremor-influx"
            covname: influx
          - project: "tremor-pipeline"
            covname: pipeline
          - project: "tremor-script"
            covname: script
          - project: "tremor-value"
            covname: value
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: sudo apt-get -qy update && sudo apt-get install -y libssl-dev libssl1.1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v1
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        env:
          PROPTEST_CASES: 2500
          RUSTFLAGS: -D warnings -C target-feature=+avx,+avx2,+sse4.2
          RUST_BACKTRACE: 1
        run: cargo llvm-cov --lcov --output-path lcov.txt -p ${{ matrix.project }} --all-targets ${{ matrix.features }}
      - uses: codecov/codecov-action@v3
        with:
          files: ./lcov.txt # optional
          flags: ${{ matrix.covname }} # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)      
